spring:
  cloud:
    gateway:
      routes:
        - id: room-service
          uri: lb://room-service
          predicates:
            - Path=/room/**
          filters:
            - AuthenticationFilter

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/reservation/**
          filters:
            - AuthenticationFilter

        - id: security-service
          uri: lb://security-service
          predicates:
            - Path=/auth/**
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
